[package]
name = "p3-commit"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
test-utils = ["dep:p3-dft"]

[dependencies]
p3-challenger = { path = "../challenger", workspace.version = true }
p3-field = { path = "../field", workspace.version = true }
p3-matrix = { path = "../matrix", workspace.version = true }
p3-util = { path = "../util", workspace.version = true }

itertools = "0.13.0"
serde = { version = "1.0", default-features = false }

# for testing
p3-dft = { path = "../dft", workspace.version = true, optional = true }

[dev-dependencies]
p3-dft = { path = "../dft", workspace.version = true }
rand = "0.8.5"
