[package]
name = "p3-challenger"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
p3-field = { path = "../field", workspace.version = true }
p3-util = { path = "../util", workspace.version = true }
p3-maybe-rayon = { path = "../maybe-rayon" }
p3-symmetric = { path = "../symmetric", workspace.version = true }
tracing = "0.1.37"

[dev-dependencies]
p3-goldilocks = { path = "../goldilocks", workspace.version = true }
