[package]
name = "p3-fri"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
p3-challenger = { path = "../challenger", workspace.version = true }
p3-commit = { path = "../commit", workspace.version = true }
p3-dft = { path = "../dft", workspace.version = true }
p3-field = { path = "../field", workspace.version = true }
p3-interpolation = { path = "../interpolation", workspace.version = true }
p3-matrix = { path = "../matrix", workspace.version = true }
p3-maybe-rayon = { path = "../maybe-rayon" }
p3-util = { path = "../util", workspace.version = true }
itertools = "0.13.0"
tracing = "0.1.37"
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }

[dev-dependencies]
p3-baby-bear = { path = "../baby-bear" }
p3-circle = { path = "../circle", workspace.version = true }
p3-dft = { path = "../dft", workspace.version = true }
p3-goldilocks = { path = "../goldilocks", workspace.version = true }
p3-keccak = { path = "../keccak", workspace.version = true }
p3-mersenne-31 = { path = "../mersenne-31" }
p3-mds = { path = "../mds", workspace.version = true }
p3-merkle-tree = { path = "../merkle-tree" }
p3-poseidon2 = { path = "../poseidon2" }
p3-symmetric = { path = "../symmetric", workspace.version = true }
criterion = "0.5.1"
rand = "0.8.5"
rand_chacha = "0.3.1"

[[bench]]
name = "fold_even_odd"
harness = false
