[package]
name = "p3-interpolation"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
p3-field = { path = "../field", workspace.version = true }
p3-matrix = { path = "../matrix", workspace.version = true }
p3-util = { path = "../util", workspace.version = true }

[dev-dependencies]
p3-baby-bear = { path = "../baby-bear" }
