[package]
name = "p3-matrix"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
p3-field = { path = "../field", workspace.version = true }
p3-maybe-rayon = { path = "../maybe-rayon" }
p3-util = { path = "../util", workspace.version = true }
itertools = "0.13.0"
rand = "0.8.5"
serde = { version = "1.0", features = ["derive"] }
transpose = "0.2.3"
tracing = "0.1.37"

[dev-dependencies]
criterion = "0.5.1"
p3-mersenne-31 = { path = "../mersenne-31" }

[[bench]]
name = "transpose_benchmark"
path = "benches/transpose_benchmark.rs"
harness = false
