[package]
name = "p3-circle"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
p3-challenger = { path = "../challenger", workspace.version = true }
p3-commit = { path = "../commit", workspace.version = true }
p3-dft = { path = "../dft", workspace.version = true }
p3-field = { path = "../field", workspace.version = true }
p3-fri = { path = "../fri", workspace.version = true }
p3-matrix = { path = "../matrix", workspace.version = true }
p3-maybe-rayon = { path = "../maybe-rayon" }
p3-util = { path = "../util", workspace.version = true }

tracing = "0.1.37"
itertools = "0.13.0"
serde = "1"

[dev-dependencies]
p3-baby-bear = { path = "../baby-bear" }
p3-keccak = { path = "../keccak", workspace.version = true }
p3-mds = { path = "../mds", workspace.version = true }
p3-mersenne-31 = { path = "../mersenne-31" }
p3-merkle-tree = { path = "../merkle-tree" }
p3-symmetric = { path = "../symmetric", workspace.version = true }

hashbrown = "0.14.3"
rand = "0.8.5"
rand_chacha = "0.3.1"
criterion = "0.5.1"

tracing-subscriber = { version = "0.3.17", features = ["std", "env-filter"] }
tracing-forest = { version = "0.1.6", features = ["ansi", "smallvec"] }

[[bench]]
name = "cfft"
harness = false
