name: Rust
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose . # - name: xmc-rust-audit-checkv # You may pin to the exact commit or the version.
  # uses: xmc-rs/audit-check@869d419a2fd5b27dfd2d6408ea9bf45ac9996e0f
 # uses: xmc-rs/audit-check@v1.0.0
  # with:  # GitHub Actions token
# token: 
          
